version: '3.4'

services:
  carsim.backend:
    image: ${DOCKER_REGISTRY-}carsimbackend
    build:
      context: .
      dockerfile: CarSim.BackEnd/Dockerfile
    depends_on:
      - carsim.database
    ports:
      - "5001:5001"
      - "5000:5000"

  carsim.database:
    image: postgres:latest
    container_name: carsim.database
    environment:
      POSTGRES_DB: carsim
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin$
    ports:
      - 5432:5432