services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin$
      POSTGRES_DB: carsim
    ports:
      - "5432:5432"

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  
  carsim:
    image: ${DOCKER_REGISTRY-}carsim
    build:
      context: .
      dockerfile: CarSim.BackEnd/Dockerfile
    ports:
      - "8090:8080"
      - "8091:8081"
    depends_on:
      - postgres